### ISSUE TITLE
Create User index page and navigation section

### ISSUE THREAD

**Issue by Willjobs94** [RVelopers/TanitaTraker-NetCore#6]

**Comment by christianrd** [comment]
@Willjobs94 What this issues about?

**Comment by Willjobs94** [comment]
It is about creating the index section for the User entity.

Something like this.

![screenshot 2018-05-16 10 05 19](https://user-images.githubusercontent.com/10265964/40121939-a8234bd8-58f0-11e8-83b0-d299adf93545.png)

**Comment by christianrd** [comment]
@Willjobs94, Is only create a View?

**Comment by Willjobs94** [comment]
Create a view that looks like that
